language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ify' ]; then cd .. && eval "mv $currentfolder generator-ify" && cd generator-ify; fi

